name: doulingo
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_bloc:
  get_it:
  dartz:
  equatable:
  flutter_svg:
  lottie:
  page_transition:
  google_sign_in:
  flutter_spinkit:
  logger:
  just_audio:
  dio:
  shared_preferences:
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail:
  bloc_test:
  mocktail_image_network:
  fake_async: ^1.3.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/
    - assets/animations/

  fonts:
    - family: Proxima Soft
      fonts:
        - asset: assets/fonts/ProximaSoft-Black.ttf
          weight: 900
        - asset: assets/fonts/ProximaSoft-Bold.ttf
        - asset: assets/fonts/ProximaSoft-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/ProximaSoft-Medium.ttf
          weight: 500
        - asset: assets/fonts/ProximaSoft-Regular.ttf
          weight: 300
        - asset: assets/fonts/ProximaSoft-SemiBold.ttf
          weight: 600
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
